### ISSUE TITLE
statusjsn.js 404

### ISSUE THREAD

**Issue by andre-wolden** [gudesystems/port.py#1]
Hi. 

I'm trying to use the API for one of these: https://gude-systems.com/en/products/expert-power-control-8080/#features

I would like to read the status as JSON. I've tried both `curl "http://<ip>/statusjsn.js?components=1"` and using `./port.py -H http://<ip>`. In both cases I get a 200 response with the following HTML:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>404 Not Found</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body><h1>ERROR 404</h1>The requested file was not found on this server.</body>
</html>
```

I'm able to turn power ports on/off with e.g.
`curl 'http://<ip>/ov.html?cmd=1&p=7&s=1' `
and
`curl 'http://<ip>/ov.html?cmd=1&p=7&s=0' `

Could you help me figure out what I'm doing wrong?

**Comment by fabian-n-gude-systems** [comment]
Dear @woldena ,
thank you very much for your request.
I am sorry to tell you that the _Expert Power Control 8080_ is one of two (older) devices, that does not provide a "statusjsn.js".

The only practical option to get the current state of all ports is by parsing the meta tags of the "ov.html" page:
```
<meta http-equiv="powerstate" content="Power Port 1,1">
<meta http-equiv="powerstate" content="Power Port 2,0">
<meta http-equiv="powerstate" content="Power Port 3,0">
<meta http-equiv="powerstate" content="Power Port 4,0">
<meta http-equiv="powerstate" content="Power Port 5,0">
<meta http-equiv="powerstate" content="Power Port 6,0">
<meta http-equiv="powerstate" content="Power Port 7,0">
<meta http-equiv="powerstate" content="Power Port 8,0">
<meta http-equiv="powerstate" content="Power Port 9,0">
<meta http-equiv="powerstate" content="Power Port 10,0">
<meta http-equiv="powerstate" content="Power Port 11,0">
<meta http-equiv="powerstate" content="Power Port 12,0">
<meta http-equiv="powerstate" content="Power Port 13,0">
<meta http-equiv="powerstate" content="Power Port 14,0">
<meta http-equiv="powerstate" content="Power Port 15,0">
<meta http-equiv="powerstate" content="Power Port 16,0">
<meta http-equiv="powerstate" content="Power Port 17,0">
<meta http-equiv="powerstate" content="Power Port 18,0">
<meta http-equiv="powerstate" content="Power Port 19,0">
<meta http-equiv="powerstate" content="Power Port 20,0">
<meta http-equiv="powerstate" content="Power Port 21,0">
<meta http-equiv="powerstate" content="Power Port 22,0">
<meta http-equiv="powerstate" content="Power Port 23,0">
<meta http-equiv="powerstate" content="Power Port 24,0"> 
```
In this example **port 1** is switched _ON_ and all **other ports** are switched _OFF_.

Hope this information helps you to solve your issue.
If you have trouble or any other problems please let us know.

**Comment by andre-wolden** [comment]
Ok, I see. Parsing the Html will work, we'll do that :+1: 

Thanks for the quick response
